import = [
  "~/.config/alacritty/theme.toml"
]

[window]
padding = { x = 0, y = 5 }

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold"

[font.bold]
family = "JetBrainsMono Nerd Font Propo"
style = "SemiBold"

[font.italic]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold Italic"
