[colors.primary]
background = "#121e1f"
foreground = "#e5e9e8"
cursor = "#e5e9e8"

[colors.normal]
black = "#121e1f"
red = "#6C8C91"
green = "#97A6AA"
yellow = "#B0BEC1"
blue = "#B9C4C5"
magenta = "#CFD8D7"
cyan = "#D7E0DF"
white = "#e5e9e8"

[colors.bright]
black = "#a0a3a2"
red = "#6C8C91"
green = "#97A6AA"
yellow = "#B0BEC1"
blue = "#B9C4C5"
magenta = "#CFD8D7"
cyan = "#D7E0DF"
white = "#e5e9e8"
