[colors.primary]
background = "#201812"
foreground = "#f5deba"
cursor = "#f5deba"

[colors.normal]
black = "#201812"
red = "#D8A76C"
green = "#EDB677"
yellow = "#DEC26F"
blue = "#FCC67C"
magenta = "#44B281"
cyan = "#E3B482"
white = "#f5deba"

[colors.bright]
black = "#ab9b82"
red = "#D8A76C"
green = "#EDB677"
yellow = "#DEC26F"
blue = "#FCC67C"
magenta = "#44B281"
cyan = "#E3B482"
white = "#f5deba"
